language: csharp

branches:
  except:
    - site-src
    - gh-pages

env:
 global:
  - EnableNuGetPackageRestore=true   
 matrix:
  - TARGET=release-mono
  - TARGET=release

install:
 - mkdir _bootstrap 
 - wget "https://github.com/vigoo/bari/releases/download/1.0.1/bari-1.0.1-mono.zip" -P _bootstrap
 - unzip _bootstrap/bari-1.0.1-mono.zip -d _bootstrap
 - mono _bootstrap/bari.exe selfupdate


script:
 - mono _bootstrap/bari.exe -v --target ${TARGET} rebuild full
 - mono _bootstrap/bari.exe -v --target ${TARGET} pack full
 - if [ "$TARGET" == "release-mono" ]; then mono _bootstrap/bari.exe -v --target ${TARGET} test && mono _bootstrap/bari.exe -v --target ${TARGET} publish full; else mono _bootstrap/bari.exe -v --target ${TARGET} publish full; fi
