language: csharp
branches:
  except:
  - site-src
  - gh-pages
env:
  global:
  - EnableNuGetPackageRestore=true
  - BUILDNO=${TRAVIS_BUILD_NUMBER}
  secure: "SnCAsyIjlJHpmXiREltgMH5S0yT46e40hOE5o8oHa0n6o1XZuyco9Bpm/z+0Qo1z+KNb2KwfR97YqF+PAjyiazuDuNrLNt19B0SRctN81eDV+0uHTwewwuGYMi4yS7Sgh6MIQ+ViB1PAKETwfunVcMzefLCsp8iX7kWAjoG75Hs="
  matrix:
  - TARGET=release-mono
  - TARGET=release
before_install:
- mkdir _bootstrap
- wget "https://github.com/vigoo/bari/releases/download/1.0.1/bari-1.0.1-mono.zip"
  -P _bootstrap
- unzip _bootstrap/bari-1.0.1-mono.zip -d _bootstrap
- mono _bootstrap/bari.exe selfupdate
script:
- git fetch
- mono _bootstrap/bari.exe -v --target ${TARGET} rebuild full
- mono _bootstrap/bari.exe -v --target ${TARGET} pack full
- (test "$TARGET" == "release-mono" && mono _bootstrap/bari.exe -v --target ${TARGET}
  test) || true
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mono
  _bootstrap/bari.exe -v --target ${TARGET} publish full
